snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/43.yaml

packages:
- xmobar

extra-deps:
  - iwlib-0.1.0
  - netlink-1.1.1.0
  - X11-1.10.3
  - X11-xft-0.3.4
  - utf8-string-1.0.2

flags:
  xmobar:
    all_extensions: true
